baseurl = "http://blog.imcdonald.com/"
languageCode = "en-gb"
title = "Ian McDonald's blog"
theme = "arabica"
author = "Ian McDonald"
paginate = 3

[params]
    description = "Random thoughts from an autistic Kiwi"
    twitter = "imcdnzl"
